name: test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Делаем gradlew исполняемым
      - run: chmod +x gradlew

      # 4. Запускаем тесты
      - run: ./gradlew clean test